### PR TITLE
Update Docs to the latest solid-start

### PR DESCRIPTION
**Pull request by birkskyum**
The docs had started to rot a bit - this puts them up to date with the latest versions of the dependencies.

The foundation of solid-start was before:

[solid-start](https://start.solidjs.com/getting-started/what-is-solidstart) -> [vite](https://vitejs.dev/)

Now it's:

[solid-start](https://start.solidjs.com/getting-started/what-is-solidstart) -> [vinxi](https://vinxi.vercel.app/) -> [vite](https://vitejs.dev/)/[nitro](https://nitro.unjs.io/)

I had to collect the CompoundExpression stuff in the compound expression file - didn't move any exported values so I don't think it'll have side effects.

The docs can be viewed by going to the /docs directory and run:
- `npm i`
- `npm run dev`
- `http://localhost:3000/maplibre-style-spec/`

A static build can also be previewed with:
- `npm run build`
- `npm run serve`
- `http://localhost:3000/maplibre-style-spec/`

### CODE REVIEW

**Comment by HarelM** [comment]
Can you elaborate on the compound expression file? it's a strange file to see in the docs as it has a lot of logic.
What does it serve?

**Comment by HarelM** [comment]
My bad, it's not in the docs, this is the style-spec package.
But we are we changing this as part of the docs change?
Is there a bug we are solving as part of this PR?

**Comment by birkskyum** [comment]
I'm investigating if I can resolve the import attribution warning.

**Comment by birkskyum** [comment]
- https://github.com/nksaraf/vinxi/issues/252

**Comment by birkskyum** [comment]
@HarelM , I found a way to support the import assert, so it can stay there and remove the warnings.

**Comment by HarelM** [comment]
Great! thanks!

**Comment by louwers** [comment]
image

**Pull request merged**
