### PR TITLE
Add Projection specifications

### PR DESCRIPTION
**Pull request by HarelM**
## Launch Checklist

This PR adds the projection specification according to the discussion here:
- #568

This is still experimental.

The following is how the docs would look like:
image

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [x] Briefly describe the changes in this PR.
 - [x] Link to related issues.
 - [x] Include before/after visuals or gifs if this PR includes visual changes.
 - [x] Write tests for all new functionality.
 - [x] Document any changes to public APIs.
 - [x] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by birkskyum** [comment]
Is this to be understood as that the provided projection will be the one for low zoom levels, and then web-mercator on high zoom, and we'll add a transition at appropriate zoom levels?

**Comment by HarelM** [comment]
The current implementation of globe transitions from globe to mercator without any zoom configurations or user input, it just does it. I don't know if we can actually keep the globe projection while zooming in further.
Having said that, this is still experimental and I want to be able to use it in the globe branch and see how it behaves and then decide if and how to change it.
CC: @kubapelc

**Review by birkskyum — APPROVED** [review]

**Comment by birkskyum** [comment]
That's a good point, as long as it's experimental this will do fine.

**Comment by kubapelc** [comment]
> The current implementation of globe transitions from globe to mercator without any zoom configurations or user input, it just does it. I don't know if we can actually keep the globe projection while zooming in further.

Hi, it needs to do that at a certain zoom level, because otherwise 32 bit floats (or GPU inverse trigonometry) will run out of precision and artifacts will appear. 

The transition zoom level (and the animation duration) is currently not configurable, but it is just a few numbers and I don't see any reason why users shouldn't be able to adjust it. The current values (possibly good candidates for default values) make the transition virtually unnoticeable, while the artifacts are also well hidden.

**Pull request merged**
