### PR TITLE
Reduce npm package files

### PR DESCRIPTION
**Pull request by HarelM**
This removes some of the files that currently exist in the npm package for no good reason, I think.
Also fixed some comments from a previous PR.

### CODE REVIEW

**Comment by neodescis** [comment]
Seems fine, but is the `files` change actually needed? I only see those things in the package already anyway. Why are we including `src` though?

https://unpkg.com/browse/maplibre-gl@3.6.2/

**Comment by HarelM** [comment]
The link is not for this package 😀
I think adding only the dist is enough, but if anyone would like to see the source that generated it, it might help, IDK...

**Comment by HarelM** [comment]
@neodescis can you approve so I could merge?

**Comment by neodescis** [comment]
> The link is not for this package 😀 I think adding only the dist is enough, but if anyone would like to see the source that generated it, it might help, IDK...

Oh, hahaha, I forgot what repo I was in!

**Review by neodescis — APPROVED** [review]

**Pull request merged**
