### PR TITLE
Add coverage to codecov and automerge to dependabot

### PR DESCRIPTION
**Pull request by HarelM**
Add coverage using codecov.

Let's see if this works...

### CODE REVIEW

**Comment by HarelM** [comment]
The report is working:
image

**Comment by HarelM** [comment]
I've also added the integration tests to the coverage report and it seems that we are at about 77%, which is OK.

I've added the auto merge of the dependabot while I'm at it...

**Review by birkskyum — APPROVED** [review]

**Comment by louwers** [comment]
> about 77%

The battle is on I guess.

**Comment by HarelM** [comment]
Seems like you're leading 😀
@nyurik you need to catch up...
Screenshot_20230629_181341_Chrome

**Pull request merged**
