### PR TITLE
Fix lists

### PR DESCRIPTION
**Pull request by wipfli**
## Launch Checklist

 - [x] Confirm **your changes do not include backports from Mapbox projects** (unless with compliant license) - if you are not sure about this, please ask!
 - [ ] Briefly describe the changes in this PR.
 - [ ] Link to related issues.
 - [ ] Include before/after visuals or gifs if this PR includes visual changes.
 - [ ] Write tests for all new functionality.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores.
 - [ ] Add an entry to `CHANGELOG.md` under the `## main` section.

### CODE REVIEW

**Comment by wipfli** [comment]
After:

image

Before (current):

image

**Comment by HarelM** [comment]
I guess the question here is if we want the doc field to be markdown ready or not. 
Up until now, I've fixed the v8 file instead of the generation script in order to have the docs as markdown ready. 
I think we can do the same here - replace new lines in v8 instead. 
In general, I prefer to update the v8 file when possible instead of complicating the generation script (less relevant for this case as it is a very simple change).

Let me know what you think.

**Comment by wipfli** [comment]
Changing the `v8.json` file is fine for me too. We can search and replace `\n-` with `\n\n-`...

**Comment by wipfli** [comment]
Closing if favor of #788

**Pull request closed without merging**
