### PR TITLE
Improve documentation for sprite

### LINKED ISSUE #389: Sprite Documentation is Outdated
MapLibre GL JS now allows multiple Sprites to be provided in a single style: https://github.com/maplibre/maplibre-gl-js/pull/1805

This part is up-to-date: https://maplibre.org/maplibre-style-spec/root/#sprite

But the [page on Sprites](https://maplibre.org/maplibre-style-spec/sprite/) makes no mention of the new array based syntax.

Also it should be mentioned that as of now, MapLibre Native does not support this new syntax. https://github.com/maplibre/maplibre-native/issues/641

cc @smellyshovel @HarelM

### PR DESCRIPTION
**Pull request by HarelM**
Fixes #389 - Sprite Documentation is Outdated
Add other data to that page.
Update some versions support in the v8 file.

### CODE REVIEW

**Comment by HarelM** [comment]
@birkskyum I was trying to make codespaces run the docs site but it didn't work well...
I did `npm i` in the root folder and `npm i && npm run build && npm run start` did I miss anything?

**Review by louwers — APPROVED** [review]

**Comment by HarelM** [comment]
@louwers did what I wrote make sense? Is it clear? Is the english OK?

**Comment by louwers** [comment]
Can I push some changes? You can see if you like them.

**Comment by louwers** [comment]
I restructered and reworded things a bit. Hope you like it.

---

I think this sentence should be removed or reworded? Do you know what it is trying to say?

> with the tokenized value  \`"icon-image": "{icon}"\` and vector tile features with an \`icon\` property with the value \`poi\`.

**Comment by HarelM** [comment]
I can't see it in comparison to the current page, did you intentionally add a md file?

**Comment by HarelM** [comment]
> I think this sentence should be removed or reworded? Do you know what it is trying to say?

Yes, it means you can use feature properies from a vector tile source to set the image icon, similar to the `["get", "icon"]` in other dynamic values, I think...

**Pull request merged**
